---
- hosts: 
    - master
    - workers
  tags: ['init']
  vars_files:
    - ./secrets/secrets.yml
  roles:
    - users
    - ssh
    - iptables
    - apt
    - docker
    - kubeadm
  gather_facts: true
- hosts:
    - master
  vars_files:
    - ./secrets/secrets.yml
  roles:
    - master_node
- hosts:
    - worker
  roles:
    - worker_node