---

- name: apt install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-requests
      - python3-urllib3
      - python3-openssl

- name: Add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  args:
    warn: false
  become: yes

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  become: yes

- name: Check available Docker CE versions
  shell: apt-cache policy docker-ce
  register: docker_policy_output
  become: yes

- name: apt install docker packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
  become: yes

- name:  Add user to docker group
  user:
    name: "{{ new_user_name }}"
    groups: docker
    append: yes
  become: yes

- name: Verify that the docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
